fix(eslint-plugin) replace interface-name-prefix
TinkoffCreditSystems/linters pull request #63
Opened 2020-09-07 10:26 UTC by zy2ba

In typescript-eslint 3.0.0 interface-name-prefix was replaced by naming-convention ([see release notes](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v3.0.0))
Implementation for replacement is taken from naming-convention examples: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/naming-convention.md#enforce-that-interface-names-do-not-begin-with-an-i

2020-09-08 08:54 UTC, SuperOleg39 requested changes

2020-09-08 10:22 UTC, zy2ba commented on packages/linters/eslint/common/typescript/conventions.js
> +                    regex: '^I[A-Z]',
I was go to last 2.x.x version for search correct equivalent for interface-name-prefix with prefixWithI: 'never' option.
Now i upgraded regexp by fully correct regexp.
[you can see this there](https://github.com/typescript-eslint/typescript-eslint/blob/f18890166146d8c6b8804ef705c04b15da269926/packages/eslint-plugin/src/rules/interface-name-prefix.ts)

del separate naming-convention from `C:\Projects\linters\packages\linters\eslint\common\typescript\conventions.js` and paste this to `C:\Projects\linters\packages\linters\eslint\common\conventions.js`  naming-convention rule

2020-09-08 10:32 UTC, zy2ba commented on packages/linters/eslint/common/typescript/conventions.js
> +                    regex: '^I[A-Z]',
I was go to last 2.x.x version for search correct equivalent for interface-name-prefix with prefixWithI: 'never' option.
Now i upgraded regexp by fully correct regexp.
[you can see this there](https://github.com/typescript-eslint/typescript-eslint/blob/f18890166146d8c6b8804ef705c04b15da269926/packages/eslint-plugin/src/rules/interface-name-prefix.ts)

del separate naming-convention from `C:\Projects\linters\packages\linters\eslint\common\typescript\conventions.js` and paste this to `C:\Projects\linters\packages\linters\eslint\common\conventions.js`  naming-convention rule

2020-09-08 14:26 UTC, SuperOleg39 commented on packages/linters/eslint/common/typescript/conventions.js
> +                    regex: '^I[A-Z]',
Good, looks like current behaviour

2020-09-08 14:27 UTC, SuperOleg39 approved these changes

2020-09-10 05:46 UTC, MarsiBarsi approved these changes

2020-10-01 09:21 UTC, merged

2020-10-01 09:40 UTC, SuperOleg39 commented
Released at `1.0.0-rc.12`